version: '3.8'
services:
  generador-documentacion-tecnica:
    container_name: generador-documentacion-tecnica
    image: python:3.13.9-alpine3.22 
    volumes:
      - ./src:/workspace
    command: sleep infinity